"""change db

Revision ID: 8f4430b7991e
Revises: c5b46d1b340f
Create Date: 2025-10-06 08:43:27.781005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4430b7991e'
down_revision = 'c5b46d1b340f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overhang_factor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stair_calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_height', sa.Float(), nullable=False),
    sa.Column('total_length', sa.Float(), nullable=False),
    sa.Column('num_steps', sa.Integer(), nullable=False),
    sa.Column('riser_height', sa.Float(), nullable=False),
    sa.Column('tread_length', sa.Float(), nullable=False),
    sa.Column('overhang', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('umore')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.create_table('umore',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stato', sa.VARCHAR(length=80), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stair_calculation')
    op.drop_table('app_config')
    # ### end Alembic commands ###
